import type { GoldScenario, GoldTurn, PlaceStub } from "./types";

/**
 * Human-authored gold for the first conversation-understanding run.
 * Expected labels describe what a person would want HAMA to keep, change, or ask.
 * They were not produced by calling the conversation functions.
 */

function deck(prefix: string, names: string[]): PlaceStub[] {
  return names.map((name, index) => ({ id: `${prefix}-${index + 1}`, name }));
}

const cafe = deck("cafe", ["동탄 골목 카페", "동탄 호수 카페", "동탄 창가 카페"]);
const cafeNext = deck("cafe-next", ["오산 골목 카페", "오산 조용한 카페", "병점 카페"]);
const play = deck("play", ["동탄 키즈플레이", "동탄 실내놀이터", "동탄 과학체험"]);
const playNext = deck("play-next", ["동탄 블록놀이", "동탄 키즈도서관", "동탄 실내체육"]);
const food = deck("food", ["동탄 한식당", "동탄 가족식당", "동탄 고기집"]);
const foodNext = deck("food-next", ["동탄 국밥집", "동탄 분식", "동탄 백반"]);
const salon = deck("salon", ["동탄 헤어샵", "동탄 네일샵", "오산 미용실"]);

type TurnInput = Partial<GoldTurn> & Pick<GoldTurn, "utterance" | "refinement">;

function written<T>(value: T | undefined, fallback: T): T {
  return value === undefined ? fallback : value;
}

function turn(input: TurnInput): GoldTurn {
  return {
    utterance: input.utterance,
    support: written(input.support, "supported"),
    refinement: input.refinement,
    category: written(input.category, "any"),
    region: written(input.region, "any"),
    withKids: written(input.withKids, "any"),
    scenario: written(input.scenario, "any"),
    indoor: written(input.indoor, "any"),
    distance: written(input.distance, "any"),
    calm: written(input.calm, "any"),
    parking: written(input.parking, "any"),
    notSpicy: written(input.notSpicy, "any"),
    weather: written(input.weather, "any"),
    foodSub: written(input.foodSub, "any"),
    linkedFood: input.linkedFood ?? false,
    playListKept: input.playListKept ?? false,
    clarification: input.clarification ?? false,
    excludePlaceIds: input.excludePlaceIds ?? [],
    rejectedCategories: input.rejectedCategories ?? [],
    excludeMenus: input.excludeMenus ?? [],
    recommendationMode: input.recommendationMode ?? "any",
    searchQuery: input.searchQuery,
    retain: input.retain ?? [],
    add: input.add ?? [],
    remove: input.remove ?? [],
    shownPlaces: input.shownPlaces ?? [],
    goldConfidence: input.goldConfidence ?? "firm",
    fixRoute: input.fixRoute ?? "rules",
    rejectionCase: input.rejectionCase ?? false,
    note: input.note,
  };
}

export const conversationScenarios: GoldScenario[] = [
  {
    id: "S01",
    title: "동탄 카페에서 지역을 바꾸고 식사를 추가",
    situation: "일반적인 장소 추천",
    turns: [
      turn({
        utterance: "동탄에서 갈 만한 카페 알려 줘",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        scenario: "any",
        withKids: false,
        indoor: false,
        distance: null,
        shownPlaces: cafe,
      }),
      turn({
        utterance: "조용한 데로",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        calm: true,
        retain: ["region", "category"],
        add: ["calm"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "오산으로 바꿔 보자",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        calm: true,
        retain: ["category", "calm"],
        note: "지역만 바뀌고 카페와 조용한 분위기는 유지",
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "밥 먹을 곳도 찾아 줘",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        calm: true,
        linkedFood: true,
        playListKept: true,
        retain: ["region", "category", "calm"],
        add: ["linkedFood"],
        note: "식사는 추가 목적이고 카페 추천을 대체하지 않음",
      }),
    ],
  },
  {
    id: "S02",
    title: "아이와 실내 놀이 후 다른 곳과 식사",
    situation: "아이 및 가족 동반",
    turns: [
      turn({
        utterance: "동탄에서 아이랑 갈 만한 곳",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        indoor: false,
        shownPlaces: play,
      }),
      turn({
        utterance: "비 오면 실내만",
        refinement: "narrow",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        indoor: true,
        weather: "rain",
        retain: ["region", "category", "withKids", "scenario"],
        add: ["indoor", "rain"],
        shownPlaces: play,
      }),
      turn({
        utterance: "너무 멀지 않게",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        weather: "rain",
        distance: "near_only",
        retain: ["region", "category", "withKids", "indoor"],
        add: ["near"],
        shownPlaces: play,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        distance: "near_only",
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids", "indoor", "distance"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "그 근처에 밥 먹을 곳도 있어?",
        refinement: ["refine", "narrow"],
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        distance: "near_only",
        linkedFood: true,
        playListKept: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        retain: ["region", "category", "withKids", "indoor", "distance"],
        add: ["linkedFood"],
        goldConfidence: "review",
        note: "근처는 거리를 좁히는 말이고, 동시에 식사 목적을 추가한다",
      }),
    ],
  },
  {
    id: "S03",
    title: "데이트 카페를 유지한 채 혼자 방문으로 바꿈",
    situation: "데이트와 혼자 방문",
    turns: [
      turn({
        utterance: "오산에서 데이트 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "오산",
        scenario: "date",
        withKids: false,
        calm: false,
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "조용한 데",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        scenario: "date",
        calm: true,
        retain: ["region", "category", "scenario"],
        add: ["calm"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "이번엔 동탄",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        scenario: "date",
        calm: true,
        retain: ["category", "scenario", "calm"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "혼자 가고 싶어",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        scenario: "solo",
        calm: true,
        retain: ["region", "category", "calm"],
        add: ["solo"],
        note: "장소 종류는 카페로 두고 동행만 혼자가 된다",
      }),
    ],
  },
  {
    id: "S04",
    title: "혼자 식사, 혼잡 회피와 가까운 다른 곳",
    situation: "데이트와 혼자 방문",
    turns: [
      turn({
        utterance: "동탄에서 혼자 밥 먹을 곳",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        withKids: false,
        shownPlaces: food,
      }),
      turn({
        utterance: "복잡한 데는 싫어",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        calm: true,
        retain: ["region", "category", "scenario"],
        add: ["calm"],
        note: "결과를 거절하는 말이 아니라 한산한 조건을 추가",
        shownPlaces: food,
      }),
      turn({
        utterance: "가까운 데",
        refinement: "narrow",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        calm: true,
        distance: "near_only",
        retain: ["region", "category", "scenario", "calm"],
        add: ["near"],
        shownPlaces: food,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        distance: "near_only",
        excludePlaceIds: ["food-1", "food-2", "food-3"],
        rejectionCase: true,
        retain: ["region", "category", "scenario", "distance"],
      }),
    ],
  },
  {
    id: "S05",
    title: "놀이 장소를 병점, 평택, 동탄으로 이동",
    situation: "지역 변경",
    turns: [
      turn({
        utterance: "동탄에서 아이랑 놀 곳",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        shownPlaces: play,
      }),
      turn({
        utterance: "이번엔 병점",
        refinement: "refine",
        category: "ACTIVITY",
        region: "병점",
        withKids: true,
        scenario: "family_kids",
        retain: ["category", "withKids", "scenario"],
        shownPlaces: play,
      }),
      turn({
        utterance: "평택은 어때",
        refinement: "refine",
        category: "ACTIVITY",
        region: "평택",
        withKids: true,
        scenario: "family_kids",
        clarification: false,
        retain: ["category", "withKids", "scenario"],
        note: "지역 제안이지 빠진 정보를 묻는 확인 질문이 아님",
        shownPlaces: play,
      }),
      turn({
        utterance: "다시 동탄으로",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        retain: ["category", "withKids", "scenario"],
      }),
    ],
  },
  {
    id: "S06",
    title: "비 오는 날 실내를 카페로 전환",
    situation: "날씨와 실내 조건",
    turns: [
      turn({
        utterance: "동탄에서 주말에 갈 곳",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        indoor: false,
        weather: null,
        shownPlaces: play,
      }),
      turn({
        utterance: "비 오니까 실내로",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        indoor: true,
        weather: "rain",
        retain: ["region", "category"],
        add: ["indoor", "rain"],
        shownPlaces: play,
      }),
      turn({
        utterance: "실내만",
        refinement: "narrow",
        category: "ACTIVITY",
        region: "동탄",
        indoor: true,
        weather: "rain",
        retain: ["region", "category", "indoor"],
        shownPlaces: play,
      }),
      turn({
        utterance: "카페로 바꿔 줘",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        indoor: "any",
        weather: "any",
        retain: ["region"],
        note: "장소 종류를 카페로 바꾸며, 실내 유지 여부는 문장에 없다",
        shownPlaces: cafe,
      }),
    ],
  },
  {
    id: "S07",
    title: "가까운 조용한 식당과 주차",
    situation: "거리 및 분위기 조건",
    turns: [
      turn({
        utterance: "오산에서 저녁 먹을 식당",
        refinement: "new_request",
        category: "FOOD",
        region: "오산",
        distance: null,
        calm: false,
        parking: false,
        shownPlaces: food,
      }),
      turn({
        utterance: "가까운 곳",
        refinement: "narrow",
        category: "FOOD",
        region: "오산",
        distance: "near_only",
        retain: ["region", "category"],
        add: ["near"],
        shownPlaces: food,
      }),
      turn({
        utterance: "조용한 분위기",
        refinement: "refine",
        category: "FOOD",
        region: "오산",
        distance: "near_only",
        calm: true,
        retain: ["region", "category", "distance"],
        add: ["calm"],
        shownPlaces: food,
      }),
      turn({
        utterance: "주차되면 좋겠어",
        refinement: "refine",
        category: "FOOD",
        region: "오산",
        distance: "near_only",
        calm: true,
        parking: true,
        retain: ["region", "category", "distance", "calm"],
        add: ["parking"],
      }),
    ],
  },
  {
    id: "S08",
    title: "보여 준 장소를 연속으로 거절",
    situation: "특정 장소 거절",
    turns: [
      turn({
        utterance: "동탄 키즈카페",
        refinement: "new_request",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        goldConfidence: "review",
        note: "키즈카페는 놀이 장소일 수도 있고 카페일 수도 있다",
        shownPlaces: play,
      }),
      turn({
        utterance: "별로야",
        refinement: "reject",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "이거 말고",
        refinement: "reject",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        excludePlaceIds: ["play-1", "play-2", "play-3", "play-next-1", "play-next-2", "play-next-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
        shownPlaces: deck("play-third", ["동탄 모래놀이", "동탄 역할놀이"]),
      }),
      turn({
        utterance: "다른 데",
        refinement: "reject",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        excludePlaceIds: [
          "play-1",
          "play-2",
          "play-3",
          "play-next-1",
          "play-next-2",
          "play-next-3",
          "play-third-1",
          "play-third-2",
        ],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
      }),
    ],
  },
  {
    id: "S09",
    title: "이미 본 매장을 빼고 조건을 추가",
    situation: "이미 본 매장 제외",
    turns: [
      turn({
        utterance: "동탄에서 조용한 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        calm: true,
        shownPlaces: cafe,
      }),
      turn({
        utterance: "아까 본 데는 빼 줘",
        refinement: "reject",
        category: "CAFE",
        region: "동탄",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        rejectionCase: true,
        retain: ["region", "category", "calm"],
        note: "직전에 보여 준 세 곳을 다시 추천하지 않음",
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "그래도 창가 쪽이면 좋겠어",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        retain: ["region", "category", "calm"],
        goldConfidence: "review",
        note: "창가는 별도 저장 필드가 없어도 카페 조건은 유지. 제외 목록은 남아야 한다",
      }),
      turn({
        utterance: "다른 곳도 봐 줘",
        refinement: "reject",
        category: "CAFE",
        region: "동탄",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3", "cafe-next-1", "cafe-next-2", "cafe-next-3"],
        rejectionCase: true,
        retain: ["region", "category", "calm"],
      }),
    ],
  },
  {
    id: "S10",
    title: "놀이 뒤 근처 식사와 순한 음식",
    situation: "후속 식사 요청",
    turns: [
      turn({
        utterance: "아이랑 동탄 실내놀이",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        indoor: true,
        shownPlaces: play,
      }),
      turn({
        utterance: "식사할 곳도 알려 줘",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        linkedFood: true,
        playListKept: true,
        retain: ["region", "category", "withKids", "indoor"],
        add: ["linkedFood"],
        shownPlaces: play,
      }),
      turn({
        utterance: "아이랑 먹을 수 있는 데로",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        linkedFood: true,
        retain: ["region", "category", "withKids", "indoor"],
        shownPlaces: food,
      }),
      turn({
        utterance: "맵지 않게",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        linkedFood: true,
        notSpicy: true,
        retain: ["region", "category", "withKids"],
        add: ["notSpicy"],
      }),
    ],
  },
  {
    id: "S11",
    title: "화성 지역을 확인한 뒤 동탄 카페",
    situation: "모호한 표현 및 확인 질문",
    turns: [
      turn({
        utterance: "화성에서 카페 가고 싶어",
        refinement: "new_request",
        category: "CAFE",
        region: null,
        clarification: true,
        note: "화성을 동탄이나 병점으로 단정하지 않고 되묻는다",
        shownPlaces: [],
      }),
      turn({
        utterance: "동탄으로 봐 줘",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        clarification: false,
        retain: ["category"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "조용한 데",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        calm: true,
        clarification: false,
        retain: ["region", "category"],
        add: ["calm"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "CAFE",
        region: "동탄",
        calm: true,
        clarification: false,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        rejectionCase: true,
        retain: ["region", "category", "calm"],
      }),
    ],
  },
  {
    id: "S12",
    title: "호수 위치를 확인한 뒤 실내와 카페",
    situation: "모호한 표현 및 확인 질문",
    turns: [
      turn({
        utterance: "호수 근처에서 산책할 곳",
        refinement: ["new_request", "narrow"],
        category: ["ACTIVITY", null],
        region: null,
        clarification: true,
        distance: "any",
        goldConfidence: "review",
        note: "호수가 어느 곳인지 묻고, 새 요청과 근처 조건이 함께 있다",
      }),
      turn({
        utterance: "동탄호수로",
        refinement: "refine",
        category: ["ACTIVITY", null],
        region: "동탄",
        clarification: false,
        retain: ["category"],
        shownPlaces: play,
      }),
      turn({
        utterance: "비 오면 실내",
        refinement: "refine",
        category: ["ACTIVITY", null],
        region: "동탄",
        indoor: true,
        weather: "rain",
        clarification: false,
        retain: ["region"],
        add: ["indoor", "rain"],
        shownPlaces: play,
      }),
      turn({
        utterance: "그럼 카페",
        refinement: ["refine", "new_request"],
        category: "CAFE",
        region: "동탄",
        clarification: false,
        goldConfidence: "review",
        note: "같은 지역에서 카페로 좁힐 수도 있고 새 요청일 수도 있다",
        shownPlaces: cafe,
      }),
    ],
  },
  {
    id: "S13",
    title: "데이트 카페에서 미용으로 주제를 바꿈",
    situation: "완전히 새로운 요청으로 전환",
    turns: [
      turn({
        utterance: "동탄 데이트 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        scenario: "date",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "아니 미용실 찾아 줘",
        refinement: "new_request",
        category: "BEAUTY",
        region: "동탄",
        scenario: "any",
        excludePlaceIds: [],
        retain: ["region"],
        note: "이전 카페 거절 목록은 비어 있고, 새 업종으로 시작한다",
        shownPlaces: salon,
      }),
      turn({
        utterance: "젤네일로",
        refinement: ["refine", "new_request"],
        category: "BEAUTY",
        region: "동탄",
        goldConfidence: "review",
        retain: ["region", "category"],
        shownPlaces: salon,
      }),
      turn({
        utterance: "오산으로 가자",
        refinement: "refine",
        category: "BEAUTY",
        region: "오산",
        retain: ["category"],
      }),
    ],
  },
  {
    id: "S14",
    title: "식당 추천 뒤 예약은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄에서 저녁 먹을 식당",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        shownPlaces: food,
      }),
      turn({
        utterance: "오늘 저녁 7시에 예약해 줘",
        support: "unsupported",
        refinement: "clarify",
        category: "FOOD",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
        note: "예약 실행은 지원하지 않으므로 확인하거나 못 한다고 밝혀야 한다",
      }),
      turn({
        utterance: "두 명이야",
        support: "unsupported",
        refinement: "clarify",
        category: "FOOD",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "창가 자리로 잡아 줘",
        support: "unsupported",
        refinement: "clarify",
        category: "FOOD",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
    ],
  },
  {
    id: "S15",
    title: "실시간 대기와 영업 여부는 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄 키즈카페 추천해 줘",
        refinement: "new_request",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        note: "키즈카페는 놀이 장소일 수도 있고 카페일 수도 있다",
        shownPlaces: play,
      }),
      turn({
        utterance: "지금 대기 없는 곳만",
        support: "unsupported",
        refinement: "clarify",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        clarification: true,
        goldConfidence: "review",
        retain: ["region", "category", "withKids"],
        fixRoute: "model",
      }),
      turn({
        utterance: "실시간 혼잡도 알려 줘",
        support: "unsupported",
        refinement: "clarify",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        clarification: true,
        goldConfidence: "review",
        retain: ["region", "category", "withKids"],
        fixRoute: "model",
      }),
      turn({
        utterance: "지금 문 연 곳만",
        support: "unsupported",
        refinement: "clarify",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        clarification: true,
        goldConfidence: "review",
        retain: ["region", "category", "withKids"],
        fixRoute: "model",
      }),
    ],
  },
  {
    id: "S16",
    title: "부모님과 한적한 한식",
    situation: "아이 및 가족 동반",
    turns: [
      turn({
        utterance: "부모님이랑 동탄에서 식사",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        scenario: "parents",
        withKids: false,
        shownPlaces: food,
      }),
      turn({
        utterance: "너무 복잡하지 않은 데",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        scenario: "parents",
        calm: true,
        retain: ["region", "category", "scenario"],
        add: ["calm"],
        shownPlaces: food,
      }),
      turn({
        utterance: "한식으로",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        scenario: "parents",
        calm: true,
        foodSub: "KOREAN",
        retain: ["region", "category", "scenario", "calm"],
        add: ["foodSub"],
        shownPlaces: food,
      }),
      turn({
        utterance: "가까운 곳",
        refinement: "narrow",
        category: "FOOD",
        region: "동탄",
        scenario: "parents",
        foodSub: "KOREAN",
        distance: "near_only",
        retain: ["region", "category", "scenario"],
        add: ["near"],
      }),
    ],
  },
  {
    id: "S17",
    title: "친구 저녁을 오산으로 옮김",
    situation: "일반적인 장소 추천",
    turns: [
      turn({
        utterance: "친구들이랑 동탄 저녁 식사",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        scenario: "friends",
        shownPlaces: food,
      }),
      turn({
        utterance: "조용한 고깃집",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        scenario: "friends",
        calm: true,
        retain: ["region", "category", "scenario"],
        add: ["calm"],
        shownPlaces: food,
      }),
      turn({
        utterance: "조용한 데는 아니어도 돼",
        refinement: "broaden",
        category: "FOOD",
        region: "동탄",
        scenario: "friends",
        calm: false,
        retain: ["region", "category", "scenario"],
        remove: ["calm"],
        shownPlaces: food,
      }),
      turn({
        utterance: "오산으로 가자",
        refinement: "refine",
        category: "FOOD",
        region: "오산",
        scenario: "friends",
        calm: false,
        retain: ["category", "scenario"],
      }),
    ],
  },
  {
    id: "S18",
    title: "카페를 식사로 바꾸고 메뉴를 제외",
    situation: "완전히 새로운 요청으로 전환",
    turns: [
      turn({
        utterance: "오산 조용한 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "오산",
        calm: true,
        linkedFood: false,
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "배고프니까 밥으로 바꿔 줘",
        refinement: "new_request",
        category: "FOOD",
        region: "오산",
        linkedFood: false,
        calm: "any",
        retain: ["region"],
        note: "추가 식사가 아니라 카페 대신 식사로 전환",
        shownPlaces: food,
      }),
      turn({
        utterance: "파스타 말고",
        refinement: "refine",
        category: "FOOD",
        region: "오산",
        foodSub: "any",
        excludeMenus: ["파스타"],
        retain: ["region", "category"],
        note: "파스타는 빼되 식당 추천은 유지",
        shownPlaces: food,
      }),
      turn({
        utterance: "한식으로",
        refinement: "refine",
        category: "FOOD",
        region: "오산",
        foodSub: "KOREAN",
        retain: ["region", "category"],
        add: ["foodSub"],
      }),
    ],
  },
  {
    id: "S19",
    title: "비 오는 날 아이 놀이와 간식",
    situation: "날씨와 실내 조건",
    turns: [
      turn({
        utterance: "비 오는 날 아이랑 동탄",
        refinement: "new_request",
        category: ["ACTIVITY", null],
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        indoor: true,
        weather: "rain",
        goldConfidence: "review",
        note: "장소 업종을 말하지 않아 액티비티로 볼 수도 있고 비워 둘 수도 있다",
        shownPlaces: play,
      }),
      turn({
        utterance: "실내 놀이",
        refinement: ["refine", "narrow"],
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        weather: "rain",
        goldConfidence: "review",
        retain: ["region", "withKids", "indoor"],
        shownPlaces: play,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids", "indoor"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "간식도 먹을 곳 있어?",
        refinement: ["refine", "clarify"],
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        linkedFood: true,
        playListKept: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        goldConfidence: "review",
        retain: ["region", "category", "withKids", "indoor"],
        add: ["linkedFood"],
        note: "질문형이지만 간식 장소를 더하는 후속 요청이다",
      }),
    ],
  },
  {
    id: "S20",
    title: "중식과 일식 메뉴를 차례로 제외",
    situation: "특정 장소 거절",
    turns: [
      turn({
        utterance: "동탄 중식 맛집",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        foodSub: "CHINESE",
        shownPlaces: food,
      }),
      turn({
        utterance: "중식 말고",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        foodSub: null,
        rejectedCategories: ["CHINESE"],
        retain: ["region", "category"],
        remove: ["foodSub"],
        note: "매장 거절이 아니라 중식 조건을 뺀다",
        shownPlaces: food,
      }),
      turn({
        utterance: "일식으로",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        foodSub: "JAPANESE",
        rejectedCategories: ["CHINESE"],
        retain: ["region", "category"],
        add: ["foodSub"],
        shownPlaces: food,
      }),
      turn({
        utterance: "일식도 말고",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        foodSub: null,
        rejectedCategories: ["CHINESE", "JAPANESE"],
        retain: ["region", "category"],
        remove: ["foodSub"],
      }),
    ],
  },
  {
    id: "S21",
    title: "중식만 보다가 음식 제한을 풀음",
    situation: "거리 및 분위기 조건",
    turns: [
      turn({
        utterance: "동탄에서 중식 맛집 찾아 줘",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        foodSub: "CHINESE",
        shownPlaces: food,
      }),
      turn({
        utterance: "중식만",
        refinement: "narrow",
        category: "FOOD",
        region: "동탄",
        foodSub: "CHINESE",
        retain: ["region", "category"],
        shownPlaces: food,
      }),
      turn({
        utterance: "중식 아니어도 돼",
        refinement: "broaden",
        category: "FOOD",
        region: "동탄",
        foodSub: null,
        retain: ["region", "category"],
        remove: ["foodSub"],
      }),
    ],
  },
  {
    id: "S22",
    title: "짧은 확인 질문 뒤 분위기와 다른 곳",
    situation: "모호한 표현 및 확인 질문",
    turns: [
      turn({
        utterance: "오산 카페 추천",
        refinement: "new_request",
        category: "CAFE",
        region: "오산",
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "뭐가 좋아?",
        refinement: "clarify",
        category: "CAFE",
        region: "오산",
        clarification: true,
        retain: ["region", "category"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "조용한 쪽",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        calm: true,
        clarification: false,
        retain: ["region", "category"],
        add: ["calm"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "CAFE",
        region: "오산",
        calm: true,
        clarification: false,
        excludePlaceIds: ["cafe-next-1", "cafe-next-2", "cafe-next-3"],
        rejectionCase: true,
        retain: ["region", "category", "calm"],
      }),
    ],
  },
  {
    id: "S23",
    title: "거절 뒤 처음부터 카페를 다시 찾음",
    situation: "완전히 새로운 요청으로 전환",
    turns: [
      turn({
        utterance: "동탄에서 아이랑 놀 곳",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        shownPlaces: play,
      }),
      turn({
        utterance: "별로야",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "처음부터 카페 추천해 줘",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        withKids: false,
        scenario: "any",
        excludePlaceIds: [],
        retain: ["region"],
        note: "이전 놀이 장소 제외 목록은 새 요청에서 비운다",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "오산으로",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        excludePlaceIds: [],
        retain: ["category"],
      }),
    ],
  },
  {
    id: "S24",
    title: "혼자 카페 중 콘센트 조건은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄에서 혼자 노트북 하기 좋은 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        scenario: "solo",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "조용한 곳으로",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        scenario: "solo",
        calm: true,
        retain: ["region", "category", "scenario"],
        add: ["calm"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "콘센트 있는 곳으로",
        support: "unsupported",
        refinement: "clarify",
        category: "CAFE",
        region: "동탄",
        scenario: "solo",
        calm: true,
        clarification: true,
        retain: ["region", "category", "scenario", "calm"],
        fixRoute: "model",
        note: "콘센트 유무는 현재 추천 조건이 아니다",
      }),
      turn({
        utterance: "가까운 데",
        refinement: "narrow",
        category: "CAFE",
        region: "동탄",
        scenario: "solo",
        calm: true,
        distance: "near_only",
        clarification: false,
        retain: ["region", "category", "scenario", "calm"],
        add: ["near"],
      }),
    ],
  },
  {
    id: "S25",
    title: "가족 외식에 주차와 아이를 더함",
    situation: "아이 및 가족 동반",
    turns: [
      turn({
        utterance: "동탄에서 가족이랑 외식할 곳",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        scenario: ["family", "family_kids"],
        parking: false,
        goldConfidence: "review",
        note: "아이 언급 전 가족 식사이므로 family 또는 family_kids 모두 허용",
        shownPlaces: food,
      }),
      turn({
        utterance: "주차되는 곳으로",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        parking: true,
        retain: ["region", "category"],
        add: ["parking"],
        shownPlaces: food,
      }),
      turn({
        utterance: "아이도 같이",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        parking: true,
        retain: ["region", "category", "parking"],
        add: ["withKids"],
        shownPlaces: food,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "FOOD",
        region: "동탄",
        withKids: true,
        parking: true,
        excludePlaceIds: ["food-1", "food-2", "food-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids", "parking"],
      }),
    ],
  },
  {
    id: "S26",
    title: "영업시간과 심야 조건은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "지금 문 연 카페만",
        support: "unsupported",
        refinement: "clarify",
        category: "CAFE",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "밤 10시 이후에도 하는 곳",
        support: "unsupported",
        refinement: "clarify",
        category: "CAFE",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "오산으로",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        clarification: false,
        retain: ["category"],
      }),
    ],
  },
  {
    id: "S27",
    title: "강아지 동반은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "강아지랑 갈 수 있는 곳",
        support: "unsupported",
        refinement: "clarify",
        category: "CAFE",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "오산에도 있어?",
        refinement: ["refine", "clarify"],
        category: "CAFE",
        region: "오산",
        clarification: "any",
        goldConfidence: "review",
        retain: ["category"],
        note: "지역을 오산으로 옮기는 말이면서 짧은 질문이기도 하다",
      }),
    ],
  },
  {
    id: "S28",
    title: "가격 상한은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄에서 혼밥",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        shownPlaces: food,
      }),
      turn({
        utterance: "1인 1만원 이하만",
        support: "unsupported",
        refinement: "clarify",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        clarification: true,
        retain: ["region", "category", "scenario"],
        fixRoute: "model",
      }),
      turn({
        utterance: "가까운 데",
        refinement: "narrow",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        distance: "near_only",
        clarification: false,
        retain: ["region", "category", "scenario"],
        add: ["near"],
        shownPlaces: food,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "FOOD",
        region: "동탄",
        scenario: "solo",
        distance: "near_only",
        excludePlaceIds: ["food-1", "food-2", "food-3"],
        rejectionCase: true,
        retain: ["region", "category", "scenario", "distance"],
      }),
    ],
  },
  {
    id: "S29",
    title: "가 본 매장 이름만 제외",
    situation: "이미 본 매장 제외",
    turns: [
      turn({
        utterance: "동탄 아이랑 실내놀이",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        shownPlaces: play,
      }),
      turn({
        utterance: "동탄 키즈플레이는 가 봤어",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        excludePlaceIds: ["play-1"],
        rejectionCase: true,
        retain: ["region", "category", "withKids", "indoor"],
        fixRoute: "model",
        note: "보여 준 목록 전체가 아니라 이름을 말한 한 곳만 제외",
        shownPlaces: playNext,
      }),
      turn({
        utterance: "나머지는 괜찮아",
        refinement: "broaden",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        excludePlaceIds: ["play-1"],
        goldConfidence: "review",
        retain: ["region", "category", "withKids"],
        note: "이미 제외한 한 곳은 유지하고 조건을 더 풀 수 있다",
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        excludePlaceIds: ["play-1", "play-next-1", "play-next-2", "play-next-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
      }),
    ],
  },
  {
    id: "S30",
    title: "식사 추가 뒤에도 놀이 조건 유지",
    situation: "후속 식사 요청",
    turns: [
      turn({
        utterance: "동탄에서 아이랑 갈 곳",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        shownPlaces: play,
      }),
      turn({
        utterance: "그 근처 식사할 곳도",
        refinement: ["refine", "narrow"],
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        linkedFood: true,
        playListKept: true,
        distance: "any",
        goldConfidence: "review",
        retain: ["region", "category", "withKids", "scenario"],
        add: ["linkedFood"],
        shownPlaces: play,
      }),
      turn({
        utterance: "맵지 않게",
        refinement: "refine",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        linkedFood: true,
        notSpicy: true,
        retain: ["region", "category", "withKids"],
        add: ["notSpicy"],
        shownPlaces: food,
      }),
      turn({
        utterance: "그 식당은 말고",
        refinement: "reject",
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        linkedFood: true,
        notSpicy: true,
        excludePlaceIds: ["food-1", "food-2", "food-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
        note: "식당 카드만 거절하고 아이와 지역은 유지",
      }),
    ],
  },
  {
    id: "S31",
    title: "비 오는 데이트 카페와 디저트",
    situation: "데이트와 혼자 방문",
    turns: [
      turn({
        utterance: "동탄에서 데이트할 곳",
        refinement: "new_request",
        category: ["CAFE", "ACTIVITY", null],
        region: "동탄",
        scenario: "date",
        goldConfidence: "review",
        note: "데이트 장소의 업종은 카페로 단정되지 않는다",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "비 와서 실내",
        refinement: "refine",
        category: ["CAFE", "ACTIVITY", null],
        region: "동탄",
        scenario: "date",
        indoor: true,
        weather: "rain",
        goldConfidence: "review",
        retain: ["region", "scenario"],
        add: ["indoor", "rain"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "카페로",
        refinement: ["refine", "new_request"],
        category: "CAFE",
        region: "동탄",
        scenario: "date",
        indoor: "any",
        goldConfidence: "review",
        retain: ["region", "scenario"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "디저트도 먹고 싶어",
        refinement: "refine",
        category: "CAFE",
        region: "동탄",
        scenario: "date",
        linkedFood: false,
        retain: ["region", "category", "scenario"],
        note: "디저트는 식당 추가가 아니라 카페 안의 조건",
      }),
    ],
  },
  {
    id: "S32",
    title: "헤어에서 네일과 다른 지역",
    situation: "완전히 새로운 요청으로 전환",
    turns: [
      turn({
        utterance: "동탄에서 머리 자르러",
        refinement: "new_request",
        category: "BEAUTY",
        region: "동탄",
        shownPlaces: salon,
      }),
      turn({
        utterance: "이번엔 네일",
        refinement: ["refine", "new_request"],
        category: "BEAUTY",
        region: "동탄",
        goldConfidence: "review",
        retain: ["region", "category"],
        shownPlaces: salon,
      }),
      turn({
        utterance: "오산으로 가자",
        refinement: "refine",
        category: "BEAUTY",
        region: "오산",
        retain: ["category"],
        shownPlaces: salon,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "BEAUTY",
        region: "오산",
        excludePlaceIds: ["salon-1", "salon-2", "salon-3"],
        rejectionCase: true,
        retain: ["region", "category"],
      }),
    ],
  },
  {
    id: "S33",
    title: "아이 장소를 거절한 뒤 순한 식사",
    situation: "아이 및 가족 동반",
    turns: [
      turn({
        utterance: "동탄 키즈카페",
        refinement: "new_request",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        note: "키즈카페는 놀이 장소일 수도 있고 카페일 수도 있다",
        shownPlaces: play,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: ["ACTIVITY", "CAFE"],
        goldConfidence: "review",
        region: "동탄",
        withKids: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "밥 먹을 곳도",
        refinement: "refine",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        goldConfidence: "review",
        linkedFood: true,
        playListKept: true,
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        retain: ["region", "category", "withKids"],
        add: ["linkedFood"],
        shownPlaces: playNext,
      }),
      turn({
        utterance: "맵지 않게",
        refinement: "refine",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        linkedFood: true,
        notSpicy: true,
        goldConfidence: "review",
        excludePlaceIds: ["play-1", "play-2", "play-3"],
        retain: ["region", "category", "withKids"],
        add: ["notSpicy"],
        shownPlaces: food,
      }),
      turn({
        utterance: "그 식당은 말고",
        refinement: "reject",
        category: ["ACTIVITY", "CAFE"],
        region: "동탄",
        withKids: true,
        linkedFood: true,
        notSpicy: true,
        goldConfidence: "review",
        excludePlaceIds: ["play-1", "play-2", "play-3", "food-1", "food-2", "food-3"],
        rejectionCase: true,
        retain: ["region", "category", "withKids"],
      }),
    ],
  },
  {
    id: "S34",
    title: "실내 놀이를 오산과 병점으로만 이동",
    situation: "지역 변경",
    turns: [
      turn({
        utterance: "동탄 실내 놀이터",
        refinement: "new_request",
        category: "ACTIVITY",
        region: "동탄",
        indoor: true,
        shownPlaces: play,
      }),
      turn({
        utterance: "이번엔 오산",
        refinement: "refine",
        category: "ACTIVITY",
        region: "오산",
        indoor: true,
        retain: ["category", "indoor"],
        shownPlaces: play,
      }),
      turn({
        utterance: "이번엔 병점",
        refinement: "refine",
        category: "ACTIVITY",
        region: "병점",
        indoor: true,
        retain: ["category", "indoor"],
        shownPlaces: play,
      }),
      turn({
        utterance: "조용한 곳으로",
        refinement: "refine",
        category: "ACTIVITY",
        region: "병점",
        indoor: true,
        calm: true,
        retain: ["region", "category", "indoor"],
        add: ["calm"],
      }),
    ],
  },
  {
    id: "S35",
    title: "막연한 외출을 지역과 아이 조건으로 좁힘",
    situation: "모호한 표현 및 확인 질문",
    turns: [
      turn({
        utterance: "심심한데 어디 가지",
        refinement: "new_request",
        category: "any",
        region: null,
        clarification: true,
        goldConfidence: "review",
        note: "지역과 장소 종류가 없어 확인 질문이 필요하다",
      }),
      turn({
        utterance: "동탄으로 해 줘",
        refinement: "refine",
        region: "동탄",
        category: "any",
        clarification: false,
        shownPlaces: play,
      }),
      turn({
        utterance: "아이랑",
        refinement: "refine",
        region: "동탄",
        withKids: true,
        scenario: "family_kids",
        category: "any",
        clarification: false,
        retain: ["region"],
        add: ["withKids"],
        shownPlaces: play,
      }),
      turn({
        utterance: "실내 놀이",
        refinement: ["refine", "narrow"],
        category: "ACTIVITY",
        region: "동탄",
        withKids: true,
        indoor: true,
        goldConfidence: "review",
        clarification: false,
        retain: ["region", "withKids"],
        add: ["indoor"],
      }),
    ],
  },
  {
    id: "S36",
    title: "데이트 코스에 식사와 실내를 반영",
    situation: "일반적인 장소 추천",
    turns: [
      turn({
        utterance: "동탄에서 데이트 코스 짜 줘",
        refinement: "new_request",
        category: "any",
        region: "동탄",
        scenario: "date",
        recommendationMode: "course",
        shownPlaces: cafe,
        note: "한 장소가 아니라 코스 추천",
      }),
      turn({
        utterance: "식사는 꼭 넣어 줘",
        refinement: "refine",
        category: "any",
        region: "동탄",
        scenario: "date",
        recommendationMode: "course",
        linkedFood: false,
        retain: ["region", "scenario"],
        note: "코스 안에 식사를 넣는 말이며 별도 식당 목록으로 바꾸라는 뜻은 아님",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "실내만",
        refinement: "narrow",
        category: "any",
        region: "동탄",
        scenario: "date",
        indoor: true,
        recommendationMode: "course",
        retain: ["region", "scenario"],
        add: ["indoor"],
        shownPlaces: cafe,
      }),
      turn({
        utterance: "세 시간 정도로",
        refinement: "refine",
        category: "any",
        region: "동탄",
        scenario: "date",
        indoor: true,
        recommendationMode: "course",
        retain: ["region", "scenario", "indoor"],
        goldConfidence: "review",
        note: "시간 길이는 별도 정답이 없고, 코스와 지역과 실내는 유지",
      }),
    ],
  },
  {
    id: "S37",
    title: "알레르기 조건은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "동탄 식당",
        refinement: "new_request",
        category: "FOOD",
        region: "동탄",
        shownPlaces: food,
      }),
      turn({
        utterance: "견과 알레르기 없는 곳",
        support: "unsupported",
        refinement: "clarify",
        category: "FOOD",
        region: "동탄",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "한식으로",
        refinement: "refine",
        category: "FOOD",
        region: "동탄",
        foodSub: "KOREAN",
        clarification: false,
        retain: ["region", "category"],
        add: ["foodSub"],
      }),
    ],
  },
  {
    id: "S38",
    title: "영어 메뉴 조건은 처리하지 못함",
    situation: "현재 기능으로 처리할 수 없는 요청",
    turns: [
      turn({
        utterance: "오산 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "오산",
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "영어 메뉴 있는 곳",
        support: "unsupported",
        refinement: "clarify",
        category: "CAFE",
        region: "오산",
        clarification: true,
        retain: ["region", "category"],
        fixRoute: "model",
      }),
      turn({
        utterance: "조용한 데",
        refinement: "refine",
        category: "CAFE",
        region: "오산",
        calm: true,
        clarification: false,
        retain: ["region", "category"],
        add: ["calm"],
      }),
    ],
  },
  {
    id: "S39",
    title: "거절을 쌓은 뒤 새 요청에서 제외 목록을 비움",
    situation: "이미 본 매장 제외",
    turns: [
      turn({
        utterance: "동탄 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "동탄",
        shownPlaces: cafe,
      }),
      turn({
        utterance: "별로야",
        refinement: "reject",
        category: "CAFE",
        region: "동탄",
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        rejectionCase: true,
        retain: ["region", "category"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "다른 곳",
        refinement: "reject",
        category: "CAFE",
        region: "동탄",
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3", "cafe-next-1", "cafe-next-2", "cafe-next-3"],
        rejectionCase: true,
        retain: ["region", "category"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "처음부터 미용실 찾아 줘",
        refinement: "new_request",
        category: "BEAUTY",
        region: "동탄",
        excludePlaceIds: [],
        retain: ["region"],
        note: "새 업종으로 바꾸면 카페 제외 목록은 따라가지 않는다",
        shownPlaces: salon,
      }),
      turn({
        utterance: "오산 네일로",
        refinement: ["refine", "new_request"],
        category: "BEAUTY",
        region: "오산",
        excludePlaceIds: [],
        goldConfidence: "review",
        retain: ["category"],
      }),
    ],
  },
  {
    id: "S40",
    title: "거기 말고는 보여 준 장소를 제외",
    situation: "특정 장소 거절",
    turns: [
      turn({
        utterance: "평택에서 조용한 카페",
        refinement: "new_request",
        category: "CAFE",
        region: "평택",
        calm: true,
        shownPlaces: cafe,
      }),
      turn({
        utterance: "거기 말고 다른 데",
        refinement: "reject",
        category: "CAFE",
        region: "평택",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        rejectionCase: true,
        retain: ["region", "category", "calm"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "그래도 조용한 데",
        refinement: "refine",
        category: "CAFE",
        region: "평택",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        retain: ["region", "category", "calm"],
        shownPlaces: cafeNext,
      }),
      turn({
        utterance: "병점으로 가자",
        refinement: "refine",
        category: "CAFE",
        region: "병점",
        calm: true,
        excludePlaceIds: ["cafe-1", "cafe-2", "cafe-3"],
        retain: ["category", "calm"],
        note: "지역만 바뀌므로 이미 뺀 매장은 계속 뺀다",
      }),
    ],
  },
];
